### ISSUE TITLE
'bundle install --path vendor' is not qualified and no path was specified

### ISSUE THREAD

**Issue by garthk** [garethr/garethr-kibana#1]
On Ubuntu precise, Puppet complains:

```
# puppet module install garethr/kibana
/etc/puppet/modules
└── garethr-kibana (v0.0.1)
# puppet apply -e 'include kibana'
Error: 'bundle install --path vendor' is not qualified and no path was specified. Please qualify the command or specify a path.
```

This might be a documentation problem rather than a Puppet module problem: I can override Exec defaults to supply a path (see workaround below). It would be cleaner to give a default path and, if necessary, provide a way for users to override it. 

Workaround:

```
package { ['rubygems', 'ruby-bundler']: # missing deps on Ubuntu
  ensure => present,
}

Exec {
  path => '/usr/local/bin:/usr/bin:/bin',
}

class { 'kibana':
  git_hash => 'f07b65e',
}

Package['rubygems'] -> Class['kibana']
Package['ruby-bundler'] -> Class['kibana']
```

I needed `git_hash` for a separate issue: the current tarchive gives you `/opt/rashidkpc-Kibana-f07b65e', where your`manifests/init.pp`defaults to`edb4553`.

**Comment by garethr** [comment]
Thanks for the heads up. I've changed the paths to be absolute for the tar and bundle command. I already had the Exec path fixes in place in my test environment and missed em. Fixed in the latest version.
