### ISSUE TITLE
KibanaConfig missing values, causing 500 errors in Kibana

### ISSUE THREAD

**Issue by garthk** [garethr/garethr-kibana#2]
The latest Kibana requires the following values in `KibanaConfig`:
- Highlight_results
- Highlighted_field
- Clickable_URLs

Without them, Kibana puts up an "Oops!" message citing a 500 Server Failure at an API URL. Trying that URL directly reveals the uninitialised constants.

**Comment by garethr** [comment]
Thanks for the heads up. I've pushed a new release that fixes this for the moment.
